territory:
  cell_width: 50
  cell_height: 50
  border_color: '#eeeeee'
  margin: 10
agents:
  radius: 10
  base_color: '#000000'
  strategy_colors:
    - '#0b62a4'
    - '#ff9f01'
    - '#0000ff'
  interaction_color: '#ffffff'
